from causalm_utils import count_num_cpu_gpu

PRETRAIN_LOSS_SCALE = 0
PRETRAIN_FP16 = False
PRETRAIN_NUM_WORKERS = count_num_cpu_gpu()[0]
PRETRAIN_REDUCE_MEMORY = False

PRETRAIN_DATA_SHORT_SEQ_PROB = 0.1
PRETRAIN_DATA_NUM_WORKERS = 4
PRETRAIN_DATA_REDUCE_MEMORY = False
PRETRAIN_DATA_WHOLE_WORD_MASK = False
LOGGER_NAME = 'experiment'

BERT_PRETRAINED_MODEL = 'bert-base-uncased'
MAX_POMS_SEQ_LENGTH = 32
MAX_SENTIMENT_SEQ_LENGTH = 384
EPOCHS = 5
MLM_PROB = 0.15
MAX_PRED_PER_SEQ = 30

CONCEPT_CLASSIFIER_MAX_DEPTH = 6
